name:                hrasspy-backend
version:             0.1.0.0
github:              "tulth/hrasspy-backend"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tulth/hrhasspy#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- warp
- wai-logger
- wai-extra
- bytestring
- transformers
- mtl
- http-conduit
- http-media
- aeson
- containers
- text
- extra
- time

library:
  source-dirs: src

executables:
  hrasspy-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wcpp-undef
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Werror
    dependencies:
    - hrasspy-backend

tests:
  hrasspy-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wcpp-undef
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Werror
    dependencies:
    - hrasspy-backend
